- name: Install dependencies
  become: yes
  apt:
    name:
      - build-essential
      - git
      - make
      - g++
      - curl
      - jq
      - vim
      - expect
    update_cache: yes
    state: present

- name: Download Go archive
  get_url:
    url: https://golang.org/dl/go1.18.linux-amd64.tar.gz
    dest: /tmp/go1.18.linux-amd64.tar.gz

- name: Extract Go archive
  become: yes
  unarchive:
    src: /tmp/go1.18.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: true
    creates: /usr/local/go
