---
- name: Set Server Timezone to {{ timezone }}
  become: yes
  become_method: sudo
  timezone:
    name: "{{ timezone }}"

- name: Install acl
  become: yes
  become_method: sudo
  apt:
    name: acl
